"""empty message

Revision ID: 0e50f3995443
Revises: 
Create Date: 2018-09-04 14:58:51.903440

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0e50f3995443'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('custom_validations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('quality_control_id', sa.Integer(), nullable=True),
    sa.Column('query_validation', sa.Text(), nullable=True),
    sa.Column('updated_on', sa.DateTime(), nullable=True),
    sa.Column('created_on', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('custom_validations')
    # ### end Alembic commands ###
