"""empty message

Revision ID: 1d2ab111d867
Revises: 6897aca028fa
Create Date: 2018-09-26 14:15:45.108321

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1d2ab111d867'
down_revision = '6897aca028fa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('custom_validations', sa.Column('implementation_key', sa.String(length=255), nullable=True))
    op.drop_column('custom_validations', 'rule_implementation_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('custom_validations', sa.Column('rule_implementation_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('custom_validations', 'implementation_key')
    # ### end Alembic commands ###
