"""empty message

Revision ID: 5139fda7a9d5
Revises: 0e50f3995443
Create Date: 2018-09-07 13:24:51.183733

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5139fda7a9d5'
down_revision = '0e50f3995443'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('custom_validations', 'quality_control_id', nullable=False, new_column_name='rule_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('custom_validations', 'rule_id', nullable=False, new_column_name='quality_control_id')
    # ### end Alembic commands ###
