"""empty message

Revision ID: 6897aca028fa
Revises: 
Create Date: 2018-09-10 12:37:45.838583

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6897aca028fa'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('custom_validations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('rule_implementation_id', sa.Integer(), nullable=True),
    sa.Column('query_validation', sa.Text(), nullable=True),
    sa.Column('updated_on', sa.DateTime(), nullable=True),
    sa.Column('created_on', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('custom_validations')
    # ### end Alembic commands ###
